# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b4bcb956121f9e28f8b5f1e35d1d4fe9ba85f8b1e25d6e7fcc7e1b82126d1eb9f7c2670c0b2b1f767f3427a500402b1e64657484ba07dff003899091c570cf1

test:
  secret_key_base: 67eb1b8e72c0da9322cb345aae81594f87b438fb0f062f8ac78d502c29a6a8a5704a10a031bd2a37442b4c67d3f08562341a1c25d0577152fd57b21c2fe3d9b3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
